#version 460

#include "cluster.glsl"

layout(local_size_x = 128) in;

#define FLT_MAX 3.402823466e+38

struct ClusterGenPushConstants {
    mat4 inv_proj;
    float znear;
    float zfar;
    uint grid_x;
    uint grid_y;
    uint grid_z;
};

layout(set = 0, binding = 0) buffer ClusterBuffer {
    ClusterConstants cluster_constants;
    ClusterData clusters[];
};

layout(push_constant) uniform Constants {
    ClusterGenPushConstants push;
};

vec3 ndc_to_view(vec3 ndc);
vec3 line_z_intersect(vec3 p1, vec3 p2, float z);

void main() {
    uint cluster_index = gl_GlobalInvocationID.x;

    if (cluster_index >= push.grid_x * push.grid_y * push.grid_z) {
        return;
    }

    uvec3 cluster_pos = uvec3(
        cluster_index % push.grid_x,
        (cluster_index / push.grid_x) % push.grid_y,
        cluster_index / (push.grid_x * push.grid_y)
    );

    // [0, grid) to NDC [-1, 1]
    vec3 grid_size = vec3(push.grid_x, push.grid_y, push.grid_z);

    cluster_constants.znear = push.znear;
    cluster_constants.zfar = push.zfar;
    cluster_constants.grid_x = push.grid_x;
    cluster_constants.grid_y = push.grid_y;
    cluster_constants.grid_z = push.grid_z;

    vec2 cluster_min = (vec2(cluster_pos.xy) / grid_size.xy) * 2.0 - 1.0;
    vec2 cluster_max = (vec2(cluster_pos.xy + uvec2(1, 1)) / grid_size.xy) * 2.0 - 1.0;

    // calculate the z values using exponential division
    float min_z = push.znear * pow(push.zfar / push.znear, float(cluster_pos.z) / grid_size.z);
    float max_z = push.znear * pow(push.zfar / push.znear, float(cluster_pos.z + 1) / grid_size.z);

    // eye in view space
    vec3 eye_vs = vec3(0.0, 0.0, 0.0);

    // calculate the four corners of the cluster in view space
    vec3 corners_vs[4] = {
        ndc_to_view(vec3(cluster_min.x, cluster_min.y, -1.0)),
        ndc_to_view(vec3(cluster_max.x, cluster_min.y, -1.0)),
        ndc_to_view(vec3(cluster_min.x, cluster_max.y, -1.0)),
        ndc_to_view(vec3(cluster_max.x, cluster_max.y, -1.0))
    };

    // extract the 'froxel' corners in view space
    vec3 cluster_bounds_min = vec3(FLT_MAX);
    vec3 cluster_bounds_max = vec3(-FLT_MAX);

    for (int i = 0; i < 4; i++) {
        vec3 near_vs = line_z_intersect(eye_vs, corners_vs[i], min_z);
        vec3 far_vs = line_z_intersect(eye_vs, corners_vs[i], max_z);

        cluster_bounds_min = min(cluster_bounds_min, near_vs);
        cluster_bounds_min = min(cluster_bounds_min, far_vs);
        cluster_bounds_max = max(cluster_bounds_max, near_vs);
        cluster_bounds_max = max(cluster_bounds_max, far_vs);
    }

    clusters[cluster_index].bounds_min = vec4(cluster_bounds_min, 0.0);
    clusters[cluster_index].bounds_max = vec4(cluster_bounds_max, 0.0);
}

vec3 line_z_intersect(vec3 p1, vec3 p2, float z) {
    return p1 + (p2 - p1) * ((z - p1.z) / (p2.z - p1.z));
}

vec3 ndc_to_view(vec3 ndc) {
    vec4 viewCoord = push.inv_proj * vec4(ndc, 1.0);
    viewCoord /= viewCoord.w;
    return viewCoord.xyz;
}
