#version 460

#include "cluster.glsl"

#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require

#define FLT_MAX 3.402823466e+38

struct ClusterAssignPushConstants {
    mat4 view;
    float light_threshold;
};

struct LightData {
    vec4 position;
    vec4 color;
    float falloff_linear;
    float falloff_quadratic;
};

layout(set = 0, binding = 0) buffer ClusterBuffer {
    ClusterConstants cluster_constants;
    ClusterData clusters[];
};

layout(set = 0, binding = 1) buffer ItemBuffer {
    // for now, uint is the light id. Later lights could be packed. -1 is empty.
    uint cluster_items_size;
    uint cluster_items[];
};

layout(set = 0, binding = 2) buffer LightBuffer {
    uint highest_light;
    LightData lights[];
};

layout(push_constant) uniform Constants {
    ClusterAssignPushConstants push;
};

bool sphere_aabb_intersect(vec3 sphere_center, float radius, vec3 aabb_min, vec3 aabb_max);
float calculate_light_radius(float linear, float quadratic);
bool light_intersects_cluster(uint light_id, vec3 cluster_min, vec3 cluster_max);

uint hash_fnv1a_init();
uint hash_fnv1a_next(uint hash, uint value);

layout(local_size_x = 128) in;

shared vec4 shared_lights[128];

void main() {
    uint cluster_index = gl_GlobalInvocationID.x;

    if (!cluster_index_valid(cluster_index, cluster_constants)) {
        return;
    }

    uint cluster_item_count = 0;
    uint cluster_item_offset = cluster_index * MAX_CLUSTER_ITEMS;

    vec3 cluster_min = clusters[cluster_index].bounds_min.xyz;
    vec3 cluster_max = clusters[cluster_index].bounds_max.xyz;

    uint hash = hash_fnv1a_init();

    uint local_index = gl_LocalInvocationID.x;
    for (uint batch_start = 0; batch_start <= highest_light; batch_start += 128) {
        // Calculate how many lights in this batch

        uint light_batch_count = min(128, highest_light + 1 - batch_start);

        // Cooperatively cache this batch of lights and calculate their radii
        // Here we can also perform an early cull if the light is outside the frustum.
        memoryBarrierShared();
        if (local_index < light_batch_count) {
            uint light_id = batch_start + local_index;

            vec4 position_ws = lights[light_id].position;
            vec3 position_vs = vec3(push.view * position_ws);
            position_vs *= -1;

            float radius = calculate_light_radius(
                lights[light_id].falloff_linear,
                lights[light_id].falloff_quadratic
            );

            vec4 packed_light = vec4(position_vs, radius);
            shared_lights[local_index] = vec4(position_vs, radius);
        }

        memoryBarrierShared();
        barrier();

        // Process this batch of lights
        for (uint i = 0; i < light_batch_count; i++) {
            uint light_id = batch_start + i;

            vec4 packed = shared_lights[i];
            if (sphere_aabb_intersect(packed.xyz, packed.w, cluster_min, cluster_max)) {
                cluster_items[cluster_item_offset + cluster_item_count] = light_id;
                cluster_item_count++;

                hash = hash_fnv1a_next(hash, light_id);
            }
        }
        barrier();
    }

    hash = hash_fnv1a_next(hash, cluster_item_count);

    uint hash_and_num_lights = hash << 8 | cluster_item_count;

    clusters[cluster_index].item_start = cluster_item_offset;
    clusters[cluster_index].hash_and_num_lights = hash_and_num_lights;
}

bool light_intersects_cluster(uint light_id, vec3 cluster_min, vec3 cluster_max) {
    vec4 light_world = lights[light_id].position;
    if (light_world.w == 0.0) return false;

    vec4 light_view = push.view * light_world;
    light_view /= light_view.w;
    light_view *= -1;

    float light_radius = calculate_light_radius(
        lights[light_id].falloff_linear, lights[light_id].falloff_quadratic
    );

    return sphere_aabb_intersect(light_view.xyz, light_radius, cluster_min, cluster_max);
}

bool sphere_aabb_intersect(vec3 sphere_center, float radius, vec3 aabb_min, vec3 aabb_max) {
    vec3 closest_point_in_aabb = clamp(sphere_center, aabb_min, aabb_max);
    float distance_sq = dot(sphere_center - closest_point_in_aabb, sphere_center - closest_point_in_aabb);
    return distance_sq < radius * radius;
}

float calculate_light_radius(float linear, float quadratic) {
    // Solve the quadratic equation to find the radius of the light

    if (quadratic > 0.0) {
        // Solve quadratic equation: att = 1/(1 + linear*d + quadratic*d^2) = threshold
        float a = quadratic;
        float b = linear;
        float c = 1.0 - (1.0/push.light_threshold);
        float discriminant = b*b - 4.0*a*c;

        if (discriminant < 0.0) return 1.0; // Fallback

        return (-b + sqrt(discriminant)) / (2.0*a);
    } else if (linear > 0.0) {
        // Linear-only attenuation
        return (1.0/push.light_threshold - 1.0) / linear;
    } else {
        return 0.0; // Default large radius for non-attenuated lights
    }
}

uint hash_fnv1a_init() {
    return 0x811c9dc5;
}
uint hash_fnv1a_next(uint hash, uint value) {
    hash ^= value;
    hash *= 0x01000193;
    return hash;
}
