#version 460

#include "cluster.glsl"

#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require

#define FLT_MAX 3.402823466e+38

struct ClusterAssignPushConstants {
    mat4 view;
    vec4 frustum_planes[6];
    float light_threshold;
};

struct LightData {
    vec4 position;
    vec4 color;
    float falloff_linear;
    float falloff_quadratic;
};

layout(set = 0, binding = 0) buffer ClusterBuffer {
    ClusterConstants cluster_constants;
    ClusterData clusters[];
};

layout(set = 0, binding = 1) buffer ItemBuffer {
    // for now, uint is the light id. Later lights could be packed. -1 is empty.
    uint cluster_items_size;
    uint cluster_items[];
};

layout(set = 0, binding = 2) buffer LightBuffer {
    uint highest_light;
    LightData lights[];
};

layout(push_constant) uniform Constants {
    ClusterAssignPushConstants push;
};

bool sphere_aabb_intersect(vec3 sphere_center, float radius, vec3 aabb_min, vec3 aabb_max);
bool sphere_frustum_intersect(vec3 sphere_center, float radius, vec4 frustum_planes[6]);
float calculate_light_radius(float linear, float quadratic, float intensity);

uint hash_fnv1a_init();
uint hash_fnv1a_next(uint hash, uint value);

layout(local_size_x = 128) in;

shared vec4 shared_lights[128];
shared uint shared_hashes[128];
shared uint shared_starts[128];
shared uint shared_first_invocation_with_hash[128];

void main() {
    uint cluster_index = gl_GlobalInvocationID.x;

    // we must let invalid cluster ids pass through as they contribute to loading
    // lights.

    uint cluster_item_count = 0;
    uint cluster_item_offset = cluster_index * MAX_CLUSTER_ITEMS;

    vec3 cluster_min;
    vec3 cluster_max;

    uint private_items[MAX_CLUSTER_ITEMS];

    if (cluster_index_valid(cluster_index, cluster_constants)) {
        cluster_min = clusters[cluster_index].bounds_min.xyz;
        cluster_max = clusters[cluster_index].bounds_max.xyz;
    }

    uint hash = hash_fnv1a_init();

    uint local_index = gl_LocalInvocationID.x;
    for (uint batch_start = 0; batch_start <= highest_light; batch_start += 128) {
        uint light_batch_count = min(128, highest_light + 1 - batch_start);

        // Cooperatively cache this batch of lights and calculate their radii
        // Here we can also perform an early cull if the light is outside the frustum.
        barrier();

        if (local_index < light_batch_count) {
            uint light_id = batch_start + local_index;

            LightData light = lights[light_id];

            vec4 position_ws = light.position;
            vec3 position = vec3(push.view * position_ws);
            position *= -1;

            float intensity = distance(light.color.rgb, vec3(0.0))
                * light.color.a;

            float radius = calculate_light_radius(
                light.falloff_linear,
                light.falloff_quadratic,
                intensity
            );

            shared_lights[local_index] = vec4(position, radius);
        }

        barrier();

        // Process this batch of lights
        if (cluster_index_valid(cluster_index, cluster_constants)) {
            for (uint i = 0; i < light_batch_count; i++) {
                if (cluster_item_count >= MAX_CLUSTER_ITEMS) break;
                uint light_id = batch_start + i;
                vec4 packed = shared_lights[i];

                if (sphere_aabb_intersect(packed.xyz, packed.w, cluster_min, cluster_max)) {
                    private_items[cluster_item_count] = light_id;
                    cluster_item_count++;
                    hash = hash_fnv1a_next(hash, light_id);
                }

                /*
                if (cluster_item_count >= MAX_CLUSTER_ITEMS) break;

                uint light_id = batch_start + i;
                vec4 packed = shared_lights[i];

                if (sphere_aabb_intersect(packed.xyz, packed.w, cluster_min, cluster_max)) {
                    cluster_items[cluster_item_offset + cluster_item_count] = light_id;
                    cluster_item_count++;
                    hash = hash_fnv1a_next(hash, light_id);
                }
                */
            }
        }
    }

    hash = hash_fnv1a_next(hash, cluster_item_count);

    shared_hashes[local_index] = hash;
    shared_first_invocation_with_hash[local_index] = 0xFFFFFFFF;
    barrier();

    if (!cluster_index_valid(cluster_index, cluster_constants)) return;

    // scan the subgroup for the first thread with the same hash as us
    for (uint i = 0; i < 128; i++) {
        if (i > local_index) continue;

        if (hash == shared_hashes[i]) {
            atomicMin(shared_first_invocation_with_hash[local_index], i);
        }
    }

    bool is_first = shared_first_invocation_with_hash[local_index] == local_index;
    uint first = shared_first_invocation_with_hash[local_index];

    if (is_first) {
        uint start = atomicAdd(cluster_items_size, cluster_item_count);
        shared_starts[local_index] = start;

        for (uint i = 0; i < cluster_item_count; i++) {
            cluster_items[start + i] = private_items[i];
        }
    }
    barrier();

    clusters[cluster_index].item_start = shared_starts[first];
    clusters[cluster_index].hash_and_num_lights = cluter_hash_and_count(hash, cluster_item_count);

    /*
    if (cluster_index_valid(cluster_index, cluster_constants)) {
        clusters[cluster_index].item_start = cluster_item_offset;
        clusters[cluster_index].hash_and_num_lights = cluter_hash_and_count(hash, cluster_item_count);
    }
    */
}

bool sphere_aabb_intersect(vec3 sphere_center, float radius, vec3 aabb_min, vec3 aabb_max) {
    vec3 closest_point_in_aabb = clamp(sphere_center, aabb_min, aabb_max);
    float distance_sq = dot(sphere_center - closest_point_in_aabb, sphere_center - closest_point_in_aabb);
    return distance_sq < radius * radius;
}

bool sphere_frustum_intersect(vec3 sphere_center, float radius, vec4 frustum_planes[6]) {
    bool intersects = true;
    for (int i = 0; i < 6; i++) {
        float distance = dot(frustum_planes[i].xyz, vec3(sphere_center)) + frustum_planes[i].w;
        intersects = intersects && distance >= -radius;
    }

    return intersects;
}

float calculate_light_radius(float linear, float quadratic, float intensity) {
    // Solve the quadratic equation to find the radius of the light

    float effective_threshold = push.light_threshold / max(intensity, 0.001);

    if (quadratic > 0.0) {
        // Solve quadratic equation: att = 1/(1 + linear*d + quadratic*d^2) = threshold
        float a = quadratic;
        float b = linear;
        float c = 1.0 - (1.0/effective_threshold);
        float discriminant = b*b - 4.0*a*c;

        if (discriminant < 0.0) return 1.0; // Fallback

        return (-b + sqrt(discriminant)) / (2.0*a);
    } else if (linear > 0.0) {
        // Linear-only attenuation
        return (1.0/effective_threshold - 1.0) / linear;
    } else {
        return 0.0;
    }
}

uint hash_fnv1a_init() {
    return 0x811c9dc5;
}
uint hash_fnv1a_next(uint hash, uint value) {
    hash ^= value;
    hash *= 0x01000193;
    return hash;
}
