#version 460

#define FLT_MAX 3.402823466e+38
#define FLT_MIN 1.175494351e-38

layout(local_size_x = 16) in;

// Object data from CPU
struct ObjectData {
    float transform[12];
    uint material_id;
    uint mesh_id;
    uint _pad[2];
};

// The draw command we'll write
struct DrawCommand {
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

struct LODData {
    uint index_start;
    uint index_count;
    float distance;
    float _pad;
};
struct MeshData {
    LODData lods[4];
    vec4 bounds_min;
    vec4 bounds_max;
};

struct CullStatistics {
    uint draw_count;
    uint draw_count_lod[4];
};

struct CullData {
    vec4 frustum_planes[6];
    vec3 eye;
};

layout(set = 0, binding = 0) readonly buffer ObjectBuffer {
    ObjectData objects[];
};

layout(set = 0, binding = 1) writeonly buffer DrawBuffer {
    uint draw_count;
    DrawCommand draws[];
};

layout(set = 0, binding = 2) readonly buffer MeshBuffer {
    MeshData meshes[];
};

layout(set = 0, binding = 3) readonly buffer CullDataBuffer {
    CullData cull_data;
};

layout(set = 0, binding = 4) buffer CullStatisticsBuffer {
    CullStatistics stats;
};

mat4 unpack_affine_transform(uint object_id) {
    float[12] transform = objects[object_id].transform;
    return mat4(
        vec4(transform[0], transform[1], transform[2], 0.0),
        vec4(transform[3], transform[4], transform[5], 0.0),
        vec4(transform[6], transform[7], transform[8], 0.0),
        vec4(transform[9], transform[10], transform[11], 1.0)
    );
}

void get_aabb(out vec3 aabb[2], uint object_id, mat4 affine_transform) {
    // determine new corners
    aabb[0] = vec3(FLT_MAX, FLT_MAX, FLT_MAX);
    aabb[1] = vec3(-FLT_MAX, -FLT_MAX, -FLT_MAX);

    vec3 corners[8];
    for (int i = 0; i < 8; ++i) {
        vec3 corner = vec3(
                (i & 1) != 0 ? meshes[objects[object_id].mesh_id].bounds_max.x : meshes[objects[object_id].mesh_id].bounds_min.x,
                (i & 2) != 0 ? meshes[objects[object_id].mesh_id].bounds_max.y : meshes[objects[object_id].mesh_id].bounds_min.y,
                (i & 4) != 0 ? meshes[objects[object_id].mesh_id].bounds_max.z : meshes[objects[object_id].mesh_id].bounds_min.z
            );
        corner = vec3(affine_transform * vec4(corner, 1.0));
        aabb[0] = min(aabb[0], corner);
        aabb[1] = max(aabb[1], corner);
    }
}

bool is_visible(uint object_id, mat4 affine_transform) {
    vec3 aabb[2];
    get_aabb(aabb, object_id, affine_transform);

    bool visible = true;
    for (int i = 0; i < 6; ++i) {
        vec3 normal = cull_data.frustum_planes[i].xyz;
        float dist = cull_data.frustum_planes[i].w;

        // get furthest point in the direction of the normal
        vec3 p = vec3(
                normal.x > 0.0 ? meshes[objects[object_id].mesh_id].bounds_max.x : meshes[objects[object_id].mesh_id].bounds_min.x,
                normal.y > 0.0 ? meshes[objects[object_id].mesh_id].bounds_max.y : meshes[objects[object_id].mesh_id].bounds_min.y,
                normal.z > 0.0 ? meshes[objects[object_id].mesh_id].bounds_max.z : meshes[objects[object_id].mesh_id].bounds_min.z
            );

        bool is_outside = dot(p, normal) + dist < 0.0;
        visible = visible && !is_outside;
    }

    return visible;
}

uint get_lod(uint object_id, mat4 affine_transform) {
    vec3 object_pos = affine_transform[3].xyz;
    float distance = distance(object_pos, cull_data.eye);

    uint lod = 0;
    for (uint i = 1; i < 4; ++i) {
        if (distance > meshes[objects[object_id].mesh_id].lods[i].distance) {
            lod = i;
        }
    }

    return lod;
}

void main() {
    uint idx = gl_GlobalInvocationID.x;
    uint object_id = idx;
    uint mesh_id = objects[object_id].mesh_id;

    // Skip invalid objects (those with no geometry)
    if (mesh_id == -1) return;

    mat4 affine_transform = unpack_affine_transform(object_id);

    if (is_visible(object_id, affine_transform)) {
        // @todo: compaction
        // Atomic add to get our draw buffer position
        uint draw_idx = atomicAdd(draw_count, 1);

        uint lod = get_lod(object_id, affine_transform);

        // Fill draw command
        draws[draw_idx].indexCount = meshes[mesh_id].lods[lod].index_count;
        draws[draw_idx].instanceCount = 1;
        draws[draw_idx].firstIndex = meshes[mesh_id].lods[lod].index_start;
        draws[draw_idx].vertexOffset = 0;
        draws[draw_idx].firstInstance = object_id;

        atomicAdd(stats.draw_count, 1);
        atomicAdd(stats.draw_count_lod[lod], 1);
    }
}
