#version 460

layout(local_size_x = 16) in;

// Object data from CPU
struct ObjectData {
    uint material_id;
    uint mesh_id;
    uint _pad[2];
    mat3x4 transform; // it is actually a 4x3 matrix, but in std140 that takes up the same as mat4.
};

// The draw command we'll write
struct DrawCommand {
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

struct LODData {
    uint index_start;
    uint index_count;
    float distance;
};
struct MeshData {
    LODData lods[4];
};

layout(set = 0, binding = 0) readonly buffer ObjectBuffer {
    ObjectData objects[];
};

layout(set = 0, binding = 1) buffer DrawBuffer {
    uint draw_count;
    DrawCommand draws[];
};

layout(set = 0, binding = 2) buffer MeshBuffer {
    MeshData meshes[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    uint object_id = idx;
    uint mesh_id = objects[object_id].mesh_id;

    // Skip invalid objects (those with no geometry)
    if (mesh_id == -1) return;

    // Atomic add to get our draw buffer position
    uint draw_idx = atomicAdd(draw_count, 1);

    // Fill draw command
    draws[draw_idx].indexCount = meshes[mesh_id].lods[0].index_count;
    draws[draw_idx].instanceCount = 1;
    draws[draw_idx].firstIndex = meshes[mesh_id].lods[0].index_start;
    draws[draw_idx].vertexOffset = 0;
    draws[draw_idx].firstInstance = object_id;
}
